#!/bin/bash
#PBS -N Wolframscript
#PBS -q bigmemlong
#PBS -l nodes=1:ppn=32:bigmem1
export PATH=$PATH:/opt/bin:/opt/Wolfram/Mathematica/12.3/SystemFiles/Kernel/Binaries/Linux-x86-64/

set queue bigmemlong resources_max.walltime=720:00:00

##ITPCluster
cd /home/fell/Documents/Github/KerrDressedWithProca/Debugging/NilsSiemonsenCode/OG_Code_MyExecution

echo "$(wolframscript -version)"

./Evaluator.wls
